# Generated by Django 3.2.6 on 2022-07-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_notemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
