# Generated by Django 3.2.6 on 2022-08-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notegroupmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notemodel',
            unique_together={('id', 'group')},
        ),
    ]
