# Generated by Django 3.2.6 on 2022-08-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notegroupmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='notemodel',
            unique_together=set(),
        ),
    ]
