# Generated by Django 3.2.6 on 2022-07-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20220714_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='text',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
